# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 854e752a0e9b91b8008dea1aa857e3d6c686b690e77f6cc568e2916dbc0282ac808c9e72d6c1c58454d8736b1137ab59e43fc78b8ee850de334196130d771827

test:
  secret_key_base: c363d9f2e1a206cae61b14bbc517efe4be60ffba79376842cabbb75b46741eadd22675d72ebcae4fe0375f421e43b7ac8d7b844ea8b9aeddd16b68b916ad076d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
